info:
  title: Order service
  profile: prod

spring:
  zipkin:
    baseUrl: zipkin:9411
  # ===== DataSource =====
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://order-db:5432/postgres
    username: postgres
    password: postgres

  # ===== Rabbit MQ =====
  rabbitmq:
    host: rabbit
    #    port: 8100
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true #true is by default
    fetchRegistry: true      #true is by default
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

keycloak:
  realm: ms-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: ms-client
  credentials:
    secret: 96cb9ee2-4966-480b-bbdb-fe5fdd2bf80d
  use-resource-role-mappings: true
  bearer-only: true
