info:
  title: Notification Service
  profile: default

server:
  port: 8006

management:
  endpoints:
    web:
      exposure:
        include: health, info, env

spring:
  zipkin:
    baseUrl: zipkin:9411
  sleuth:
    sampler:
      percentage: 1

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true #true is by default
    fetchRegistry: true      #true is by default
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/
